### ISSUE TITLE
Domain Expired

### ISSUE THREAD

**Issue by KnightDev** [ata4/mineshot#14]
The domain that your download link was hosted on, that you linked to from minecraftforum.net, has expired and is pending deletion or renewal. Direct download for 1.7.10 please?

**Comment by MggMuggins** [comment]
Try the releases page. :P 
I'm going to see if I can take up development of this completely open-source little mod. Hopefully @ata4 notices and gives me write access...

**Comment by sachk** [comment]
@MggMuggins 

You can always start a fork yourself on a separate repository.

**Comment by MggMuggins** [comment]
Yeah, I know. There's actually not much to do. The mod works just fine for the purposes of the community I'm representing here. (Also I can't make heads or tails of the code...)
